name: Publish Docker image

on:
 push:
    branches:
      - 'main' 

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: docker build -t ghcr.io/nikitakalmykov03/python:1.0 .

      - name: Docker push
        run: docker push ghcr.io/nikitakalmykov03/python:1.0

  run_image:
    name: Run Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: push_to_registries
    steps:
      - name: Docker run
        run: docker run ghcr.io/nikitakalmykov03/python:1.0
      - run: ssh -o "StrictHostKeyChecking no" 'nikitakalmykov03-python-g836p1w5kyk@nikitakalmykov03-python-g836p1w5kyk.ssh.ws-eu106.gitpod.io' "cd /workspace/nikitakalmykov03/python && docker compose pull && docker compose up -d"
